# permissions for end users to view contractors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: contractor-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubernetes
    app.kubernetes.io/part-of: kubernetes
    app.kubernetes.io/managed-by: kustomize
  name: contractor-viewer-role
rules:
- apiGroups:
  - t3kton.t3kton.com
  resources:
  - contractors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - t3kton.t3kton.com
  resources:
  - contractors/status
  verbs:
  - get
