---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - t3kton.t3kton.com
  resources:
  - contractors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - t3kton.t3kton.com
  resources:
  - contractors/finalizers
  verbs:
  - update
- apiGroups:
  - t3kton.t3kton.com
  resources:
  - contractors/status
  verbs:
  - get
  - patch
  - update
